### ISSUE TITLE
Build fails with Qt 5.15.2

### ISSUE THREAD

**Issue by schnitzeltony** [lirios/materialdecoration#11]
Yocto's meta-qt5 just upgraded Qt 5.15.0 -> 5.15.2. Now materialdecoration fails with

   71 | #include <QtXkbCommonSupport/private/qxkbcommon_p.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Yes they mean it

**Comment by ghost** [comment]
@plfiorini I am also facing this same issue.
