### ISSUE TITLE
QGnomePlatform

### ISSUE THREAD

**Issue by rmader** [lirios/materialdecoration#6]
I just stumbled over this project and wondered if it would be possible to adapt it to be used in QGnomePlatform/adwaita-qt on Wayland (or forked so it works well for Gnome and can be shipped by distributions with Gnome if they choose to).

So a couple of questions from my side:

1. Do you think it's easily possible to adapt it to other styles?
2. Does this make use of XDG-Decoration on Wayland?
3. In general, does it work well on Wayland?

Regards and thanks it advance!

See also https://github.com/FedoraQt/QGnomePlatform/issues/15#issuecomment-508571505

**Comment by plfiorini** [comment]
Qt applications using the Wayland QPA plugin (-platform wayland or when autodetected based on the current session) can load plugins like this one, that provide a Material Design compliant title bar.

You can implement new plugins with different graphic styles, however there are some limitations for example the API has not the concept of drop shadows. Perhaps you can still implement it, but the API is lackluster IMHO and not guaranteed to be stable.

When Qt is updated, you will need to rebuild QtWayland decoration plugins.

QtWayland internally uses XDG-Decoration.
